# Generated by Django 3.1.4 on 2021-01-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hello',
            new_name='hw',
        ),
    ]
